services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
      pip install -r requirements.txt
    startCommand: python your_app_file.py